alias tailtopic="docker exec  tcell_kafka_1 /opt/kafka_2.11-0.10.1.0/bin/kafka-console-consumer.sh --zookeeper zookeeper --from-beginning --topic"
alias lstopics="docker exec  tcell_kafka_1 /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh --zookeeper zookeeper --list"
alias dc="docker-compose"
alias dcc="docker-compose"
alias ssh-xhyve="docker run --rm -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh"
alias cdja="cd ${TCELL_SRC_ROOT}//agents/jvm/"
alias startportainer="docker run --name portainer --privileged -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer"
alias chrome-insecure="'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --disable-web-security --user-data-dir=${HOME}/dev/chrome_data_dir --no-default-browser-check"
alias k="kubectl"
alias kpods="kubectl get pods"
alias kprod0=". ~/.kube/setprod0.sh"
alias kprod1=". ~/.kube/setprod1.sh"
alias kprod4=". ~/.kube/setprod4.sh"
alias kprod5=". ~/.kube/setprod5.sh"
alias kstage=". ~/.kube/setstage.sh"
alias casstunnelstage="ssh -A -L 9042:10.0.11.98:9042 -L 9160:10.0.11.98:9160 -L 9142:10.0.11.98:9142 ec2-3-223-136-203.compute-1.amazonaws.com"
alias vi="/usr/local/bin/vim"
alias ecr-login-stage="AWS_PROFILE=awsaml-606696011804 aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 606696011804.dkr.ecr.us-east-1.amazonaws.com"
alias pivnc-forward="ssh -L 5900:localhost:5901  pi@10.18.1.13"
alias pivnc="echo 'be sure to port forward with pivnc-forward'; open vnc://10.18.1.13:5900"
alias k8sproxy="kubectl run --restart=Never --image=alpine/socat temp-paul -- -d -d tcp-listen:5432,fork,reuseaddr tcp-connect:172.20.64.93:5432"
